title: Compound III Documentation Site
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

## Page Name Anchor Text: Anchor HREF
v3_nav_data:
  # Compound III: / ## This is now a toggle switch between v2 and v3 docs
  Interest Rates: /interest-rates/
  Collateral & Borrowing: /collateral-and-borrowing/
  Liquidation: /liquidation/
  Account Management: /account-management/
  Protocol Rewards: /protocol-rewards/
  Governance: /governance/
  Helper Functions: /helper-functions/

