title: Compound III Documentation Site
# baseurl: /docs
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
      disable: true
## Page Name Anchor Text: Anchor HREF
nav_data:
  Compound III: /
  Interest Rates: /interest-rates/
  Collateral & Borrowing: /collateral-and-borrowing/
  Liquidation: /liquidation/
  Governance: /governance/
  Protocol Rewards: /protocol-rewards/
  Account Management: /account-management/
  Helper Functions: /helper-functions/
