title: Bitlend Documentation Site
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# ## Page Name Anchor Text: Anchor HREF
# v3_nav_data:
#   # Bitlend III: / ## This is now a toggle switch between v1 and v3 docs
#   Interest Rates: /interest-rates/
#   Collateral & Borrowing: /collateral-and-borrowing/
#   Liquidation: /liquidation/
#   Account Management: /account-management/
#   Protocol Rewards: /protocol-rewards/
#   Governance: /governance/
#   Helper Functions: /helper-functions/

v1_nav_data:
  bTokens: /v1/btokens/
  Comptroller: /v1/comptroller/
  Governance: /v1/governance/
  Open Price Feed: /v1/prices/
  # API: /v1/api/
  # Bitlend.js: /v1/compound-js/
  Security: /v1/security/
