title: Bitlend Documentation Site
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# ## Page Name Anchor Text: Anchor HREF
# v3_nav_data:
#   # Bitlend: / ## This is now a toggle switch between v1 and v3 docs
#   Interest Rates: /interest-rates/
#   Collateral & Borrowing: /collateral-and-borrowing/
#   Liquidation: /liquidation/
#   Account Management: /account-management/
#   Protocol Rewards: /protocol-rewards/
#   Governance: /governance/
#   Helper Functions: /helper-functions/

## Page Name Anchor Text: Anchor HREF
v1_nav_data:
  Introduction: /
  Guides: /guides/
  bTokens: /btokens/
  Comptroller: /comptroller/
  Tokennomics: /tokenomics/
  Protocol Parameters: /protocol-parameters/
  Security: /security/
  Roadmap: /roadmap/
